add_newline         = false
command_timeout     = 1000
follow_symlinks     = true
palette             = "mine"
continuation_prompt = '[î‚° ](fg:97 bg:none bold)'

# Format of the prompt.
format = """
$os\
$time\
$directory\
$fill\
$cmd_duration\
$status\
$jobs\
$git_branch$git_commit$fill$git_state$git_status\
$line_break\
$username\
$hostname\
$character
"""

# Custom palette is oriented around xterm-256colour.  This probably wont
# work that well in older terminals.
#
# See https://i.sstatic.net/KTSQa.png for colour values.
[palettes.mine]
user_norm      = "183"
user_root      = "196"
host_bg        = "16"
host_fg        = "172"
host_at        = "250"
time_bg        = "97"
time_fg        = "253"
os_bg          = "253"
os_fg          = "16"
dir_bg         = "16"
dir_fg         = "183"
bar_bg         = "none"
bar_fg         = "242"
red            = "88"
black          = "16"
git_branch_bg  = "97"
git_branch_fg  = "253"
git_commit_bg  = "16"
git_commit_fg  = "183"
git_status_bg  = "236"
git_status_fg  = "253"
git_ahead      = "green"
git_behind     = "179"
git_diverged   = "196"
git_uptodate   = "green"
git_conflicted = "yellow"
git_untracked  = "bright-blue"
git_stashed    = "purple"
git_modified   = "202"
git_staged     = "bright-green"
git_renamed    = "bright-cyan"
git_deleted    = "red"
duration_bg    = "105"
duration_fg    = "16"
jobs_bg        = "106"
jobs_fg        = "16"
status_bg      = "yellow"
status_fg      = "16"
status_err     = "196"
status_ok      = "bright-green"

[os]
format   = '[ $symbol ](fg:os_fg bg:os_bg bold)[î‚°](bg:time_bg fg:os_bg)'
disabled = false

# OS symbols.
#
# This is just a small subset of what's available, because I don't use it all.
[os.symbols]
Amazon           = 'ï‰°'
AlmaLinux        = "ïŒ "
Arch             = 'ïŒƒ'
Debian           = 'ïŒ†'
EndeavourOS      = 'ïŒ¢'
FreeBSD          = 'ïŒŒ'
Linux            = 'ï…¼'
Macos            = 'ïŒ‚'
NetBSD           = 'ï…¼'
Raspbian         = 'ïŒ•'
Redhat           = 'ïŒ–'
RedHatEnterprise = 'ïŒ–'
Ubuntu           = 'ïŒ›'
Unknown          = 'ï„ˆ'
Windows          = 'îœ'

# Time block.
#
# Prints basic time and date.  Nothing fancy.
[time]
format      = "[ $time ]($style)[î‚°](fg:time_bg bg:dir_bg)"
style       = "bg:time_bg fg:time_fg bold"
time_format = "%H:%M:%S"
use_12hr    = false
disabled    = false

# "Character" block.  This represents ye olde "$" and "#".
#
# This displays a green lambda if stuff is great, or just a red blob to
# indicate that an error was returned.
[character]
format         = "$symbol"
error_symbol   = "[ Î» ](bold bg:host_bg fg:status_err bold)[î‚°](fg:host_bg bg:none) "
success_symbol = "[ Î» ](bold bg:host_bg fg:status_ok bold)[î‚°](fg:host_bg bg:none) "

# Fill block.
#
# Used when right-aligning.
[fill]
symbol = ' '
style  = 'bg:none'

# Package count.
#
# We don't want this.
[package]
disabled = false

# Command duration block.
#
# So now I know just how long I'm in irc or emacs.
[cmd_duration]
min_time          = 1000
show_milliseconds = false
disabled          = false
format            = "[î‚²](bg:bar_bg fg:duration_bg)[ó°Œ $duration]($style)[î‚°](bg:bar_bg fg:duration_bg)"
style             = "bg:duration_bg fg:duration_fg"

# Command exit status block.
[status]
style    = "bg:status_bg fg:status_fg"
format   = "[î‚²](bg:bar_bg fg:status_bg)[$symbol$status]($style)[î‚°](bg:bar_bg fg:status_bg)"
disabled = false

# Shell jobs.
[jobs]
threshold        = 1
number_threshold = 1
symbol           = "â§› "
style            = "bg:jobs_bg fg:jobs_fg"
format           = "[î‚²](bg:bar_bg fg:jobs_bg)[$symbol$number]($style)[î‚°](bg:bar_bg fg:jobs_bg)"
disabled         = false

# Current working directory block.
[directory]
truncation_length = 5
truncate_to_repo  = false
truncation_symbol = "â€¦"
format            = "[ ó°· $path ]($style)[$lock_symbol]($lock_style)[î‚°](fg:dir_bg bg:bar_bg)"
style             = "fg:dir_fg bg:dir_bg"
read_only         = "ğŸ”’"
read_only_style   = "bold red"

# Current username block.
#
# Has special handling for root.
[username]
show_always = true
disabled    = false
style_user  = "bold fg:user_norm bg:host_bg"
style_root  = "bold fg:user_root bg:host_bg"
format      = '[ $user]($style)'

# Hostname block.
[hostname]
format   = "[@]($style fg:host_at)[$hostname]($style bold)"
ssh_only = false
trim_at  = "."
disabled = false
style    = "bg:host_bg fg:host_fg"

# Git commit block.
[git_commit]
disabled           = false
commit_hash_length = 8
only_detached      = false
tag_disabled       = false
format             = '[ $hash$tag ]($style)[î‚°](bg:bar_bg fg:git_commit_bg)'
style              = "bg:git_commit_bg fg:git_commit_fg"

# Git branch block.
[git_branch]
format = "\n[ ó°˜¬ ](fg:os_fg bg:os_bg bold)[î‚°](bg:git_branch_bg fg:os_bg)[ $branch ]($style)[î‚°](bg:git_commit_bg fg:git_branch_bg)"
style  = "bg:git_branch_bg fg:git_branch_fg bold"

# Git status block.
[git_status]
disabled   = false
format     = "[î‚²](bg:bar_bg fg:git_status_bg)[$all_status$ahead_behind]($style)[î‚°](bg:bar_bg fg:git_status_bg)"
style      = "fg:git_status_fg bg:git_status_bg"
ahead      = "[ ğŸ …${count} ](fg:git_ahead bg:git_status_bg bold)"
behind     = "[ ğŸ ‡${count} ](fg:git_behind bg:git_status_bg bold)"
diverged   = "[ â®½ğŸ …${ahead_count}ğŸ ‡${behind_count} ](fg:git_diverged bg:git_status_bg bold)"
up_to_date = "[ âœ” ](fg:git_uptodate bg:git_status_bg bold)"
conflicted = "[ â‰${count} ](fg:git_conflicted bg:git_status_bg bold)"
untracked  = "[ ?${count} ](fg:git_untracked bg:git_status_bg bold)"
stashed    = "[ âš¶${count} ](fg:git_stashed bg:git_status_bg bold)"
modified   = "[ !${count} ](fg:git_modified bg:git_status_bg bold)"
staged     = "[ +${count} ](fg:git_staged bg:git_status_bg bold)"
renamed    = "[ Â»${count} ](fg:git_renamed bg:git_status_bg bold)"
deleted    = "[ âœ˜${count} ](fg:git_deleted bg:git_status_bg bold)"

# Git state block.
[git_state]
disabled = false
format   = '\([$state( $progress_current/$progress_total)]($style)\) '
style    = "fg:cyan bg:git_branch_bg"

# EOF
