add_newline         = false
command_timeout     = 1000
follow_symlinks     = true
palette             = "mine"
continuation_prompt = '[ÓÇ∞ ](fg:97 bg:none bold)'

# Format of the prompt.
format = """
$os\
$username\
$time\
$directory\
$fill\
$cmd_duration\
$status\
$jobs\
$git_branch$git_commit$fill$git_state$git_status\
$line_break\
$hostname\
$character
"""

# Custom palette is oriented around xterm-256colour.  This probably wont
# work that well in older terminals.
#
# See https://i.sstatic.net/KTSQa.png for colour values.
[palettes.mine]
usernorm  = "bright-white"
userroot  = "210"
userbg    = "97"
hostlfg   = "172"
hostfg    = "202"
hostbg    = "none"
timebg    = "236"
timefg    = "252"
osbg      = "bright-white"
osfg      = "16"
dirbg     = "16"
dirfg     = "147"
barbg     = "none"
barfg     = "242"
gitfg     = "16"
durbg     = "105"
durfg     = "16"
jobbg     = "106"
jobfg     = "16"
statbg    = "yellow"
statfg    = "16"
red       = "88"
black     = "16"
gitbg     = "150"#"208"
gitlogobg = "202"
gitlogofg = "16"
gitcmt    = "105"#"214"
gitahd    = "green"
gitbhd    = "179"
gitdvd    = "196"
gitupd    = "green"
gitcnfl   = "yellow"
gitstsh   = "purple"
gitmodi   = "202"
gitstgd   = "bright-green"
gitrend   = "bright-cyan"
gituntr   = "bright-blue"
gitdeld   = "red"
staterr   = "196"
statok    = "bright-green"

[os]
format   = '[ $symbol ](fg:osfg bg:osbg bold)[ÓÇ∞](bg:userbg fg:osbg)'
disabled = false

# OS symbols.
#
# This is just a small subset of what's available, because I don't use it all.
[os.symbols]
Amazon           = 'Ôâ∞'
AlmaLinux        = "Ôåù "
Arch             = 'ÔåÉ'
Debian           = 'ÔåÜ'
EndeavourOS      = 'Ôå¢'
FreeBSD          = 'Ôåå'
Linux            = 'ÔÖº'
Macos            = 'ÔåÇ'
NetBSD           = 'ÔÖº'
Raspbian         = 'Ôåï'
Redhat           = 'Ôåñ'
RedHatEnterprise = 'Ôåñ'
Ubuntu           = 'Ôåõ'
Unknown          = 'ÔÑà'
Windows          = 'Óúè'

# Time block.
#
# Prints basic time and date.  Nothing fancy.
[time]
format      = "[ $time ]($style)[ÓÇ∞](fg:timebg bg:dirbg)"
style       = "bg:timebg fg:timefg bold"
time_format = "Û∞¶ñ %H:%M:%S"
use_12hr    = false
disabled    = false

# "Character" block.  This represents ye olde "$" and "#".
#
# This displays a green lambda if stuff is great, or just a red blob to
# indicate that an error was returned.
[character]
format         = "$symbol"
error_symbol   = "[ Œª ](bold bg:black fg:staterr bold)[ÓÇ∞](fg:black bg:none) "
success_symbol = "[ Œª ](bold bg:black fg:statok bold)[ÓÇ∞](fg:black bg:none) "

# Fill block.
#
# Used when right-aligning.
[fill]
symbol = ' '
style  = 'bg:none'

# Package count.
#
# We don't want this.
[package]
disabled = false

# Command duration block.
#
# So now I know just how long I'm in irc or emacs.
[cmd_duration]
min_time          = 1000
show_milliseconds = false
disabled          = false
format            = "[ÓÇ≤](bg:barbg fg:durbg)[Û∞ûå $duration]($style)[ÓÇ∞](bg:none fg:durbg)"
style             = "bg:durbg fg:durfg"

# Current working directory block.
[directory]
truncation_length = 3
truncate_to_repo  = false
truncation_symbol = "‚Ä¶"
format            = "[ Û∞∑è $path ]($style)[$lock_symbol]($lock_style)[ÓÇ∞](fg:dirbg bg:barbg)"
style             = "fg:dirfg bg:dirbg"
read_only         = "üîí"
read_only_style   = "bold red"

# Current username block.
#
# Has special handling for root.
[username]
show_always = true
disabled    = false
style_user  = "bold fg:usernorm bg:userbg"
style_root  = "bold fg:userroot bg:userbg"
format      = '[ $user ]($style)[ÓÇ∞]($style inverted fg:timebg)'

# Hostname block.
[hostname]
format   = "[ üñß ]($style fg:hostlfg)[$hostname]($style bold)"
ssh_only = true
trim_at  = "."
disabled = false
style    = "bg:black fg:hostfg"

# Command exit status block.
[status]
style    = "bg:statbg fg:statfg"
format   = "[ÓÇ≤](bg:barbg fg:statbg)[$symbol$status]($style)[ÓÇ∞](bg:barbg fg:statbg)"
disabled = false

[jobs]
threshold        = 1
number_threshold = 1
symbol           = "‚ßõ "
style            = "bg:jobbg fg:jobfg"
format           = "[ÓÇ≤](bg:barbg fg:jobbg)[$symbol$number]($style)[ÓÇ∞](bg:barbg fg:jobbg)"
disabled         = false

# Git commit block.
[git_commit]
disabled           = false
commit_hash_length = 8
only_detached      = false
tag_disabled       = false
format             = '[ $hash$tag ]($style)[ÓÇ∞](bg:bar fg:gitcmt)'
style              = "bg:gitcmt fg:gitfg"

# Git branch block.
[git_branch]
format = "\n[ Û∞ò¨ $branch ]($style)[ÓÇ∞](bg:gitcmt fg:gitbg)"
style  = "bg:gitbg fg:gitfg"

# Git status block.
[git_status]
disabled   = false
format     = "[$all_status$ahead_behind]($style)"
style      = "fg:gitfg bg:barbg"
ahead      = "[ÓÇ≤](bg:barbg fg:gitahd)[ü†Ö](fg:gitfg bg:gitahd bold)[ÓÇ∞](bg:barbg fg:gitahd)"
behind     = "[ÓÇ≤](bg:barbg fg:gitbhd)[ü†á](fg:gitfg bg:gitbhd bold)[ÓÇ∞](bg:barbg fg:gitbhd)"
diverged   = "[ÓÇ≤](bg:barbg fg:gitdvd)[‚ÆΩ](fg:gitfg bg:gitdvd bold)[ÓÇ∞](bg:barbg fg:gitdvd)"
up_to_date = "[ÓÇ≤](bg:barbg fg:gitupd)[‚úî](fg:gitfg bg:gitupd bold)[ÓÇ∞](bg:barbg fg:gitupd)"
conflicted = "[ÓÇ≤](bg:barbg fg:gitcnfl)[‚Åâ $count](fg:gitfg bg:gitcnfl bold)[ÓÇ∞](bg:barbg fg:gitcnfl)"
untracked  = "[ÓÇ≤](bg:barbg fg:gituntr)[? $count](fg:gitfg bg:gituntr bold)[ÓÇ∞](bg:barbg fg:gituntr)"
stashed    = "[ÓÇ≤](bg:barbg fg:gitstsh)[‚ö∂ $count](fg:gitfg bg:gitstsh bold)[ÓÇ∞](bg:barbg fg:gitstsh)"
modified   = "[ÓÇ≤](bg:barbg fg:gitmodi)[! $count](fg:gitfg bg:gitmodi bold)[ÓÇ∞](bg:barbg fg:gitmodi)"
staged     = "[ÓÇ≤](bg:barbg fg:gitstgd)[+ $count](fg:gitfg bg:gitstgd bold)[ÓÇ∞](bg:barbg fg:gitstgd)"
renamed    = "[ÓÇ≤](bg:barbg fg:gitrend)[¬ª $count](fg:gitfg bg:gitrend bold)[ÓÇ∞](bg:barbg fg:gitrend)"
deleted    = "[ÓÇ≤](bg:barbg fg:gitdeld)[‚úò $count](fg:gitfg bg:gitdeld bold)[ÓÇ∞](bg:barbg fg:gitdeld)"

# Git state block.
[git_state]
disabled = false
format   = '\([$state( $progress_current/$progress_total)]($style)\) '
style    = "fg:cyan bg:gitbg"

# EOF
